import {
  Building2,
  SprayCan,
  Waves,
  Layers,
  PanelsTopLeft,
  KeyRound,
  Gem,
  Phone,
  Mail,
  ArrowRight,
  ArrowUpRight,
  Check,
  CheckCircle2,
  Star,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  MapPin,
  Quote,
  Leaf,
  ShieldCheck,
  Clock,
  Sparkles,
  Recycle,
  Users,
  Award,
  BadgeCheck,
  Building,
  type LucideIcon,
} from "lucide-react";

export const icons = {
  Building2,
  SprayCan,
  Waves,
  Layers,
  PanelsTopLeft,
  KeyRound,
  Gem,
  Phone,
  Mail,
  ArrowRight,
  ArrowUpRight,
  Check,
  CheckCircle2,
  Star,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  MapPin,
  Quote,
  Leaf,
  ShieldCheck,
  Clock,
  Sparkles,
  Recycle,
  Users,
  Award,
  BadgeCheck,
  Building,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({ name, className, strokeWidth = 1.75 }: { name: IconName; className?: string; strokeWidth?: number }) {
  const Cmp = icons[name] ?? Sparkles;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
